Repository 100-hours-a-week/10-team-joytas-dao-be, pull requests merged in 2024-09, with the labels that each got.

#163 Refactor/objet
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#165 채팅 도메인 1차 리팩토링
  src/main/java/com/example/daobe/chat/application/ChatRoomService.java
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/domain/MessageType.java
  src/main/java/com/example/daobe/chat/exception/ChatException.java
  src/main/java/com/example/daobe/chat/exception/ChatExceptionType.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
Labels: 리팩토링

#166 알림 도메인 레이어별 역할 재정의
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationSubscribeService.java
  src/main/java/com/example/daobe/notification/domain/NotificationEmitter.java
  src/main/java/com/example/daobe/notification/domain/repository/EmitterRepository.java
  src/main/java/com/example/daobe/notification/infrastructure/in_memory/InMemoryEmitterRepository.java
Labels: 리팩토링

#167 활성 상태가 아닌 라운지 조회시 404 예외 던지도록 수정
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
Labels: 버그-일반

#169 오브제 이미지 업로드 분리
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateRequestDto.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#170 refactor: 불필요한 이미지 업로드 엔드포인트 삭제
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#173 오브제 수정 삭제 sharers 데이터 타입 변경
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateRequestDto.java
Labels: 리팩토링

#175 refactor: 오브제 상세 조회 응답 데이터에 lounge_id 추가
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
Labels: 리팩토링

#178 레디스 설정 및 개발 서버 이미지 태그명 수정
  .github/workflows/backend-dev-cd.yml
  src/main/java/com/example/daobe/common/config/RedisConfig.java
Labels: 리팩토링

#179 사용자 도메인 이벤트 및 이벤트 발행 로직 추가
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/domain/event/UserCreateEvent.java
  src/main/java/com/example/daobe/user/domain/event/UserUpdateEvent.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 기능추가

#180 채팅 메시지 유저 데이터 동기화 기능 추가
  docker/init.js
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/application/event/ChatUserEventListener.java
  src/main/java/com/example/daobe/chat/domain/ChatMessage.java
  src/main/java/com/example/daobe/chat/domain/ChatUser.java
  src/main/java/com/example/daobe/chat/domain/repository/ChatUserRepository.java
Labels: 버그-일반, 기능추가, 리팩토링

#184 알림 전송시 Redis PUB/SUB 이벤트 발행 로직 추가
  src/main/java/com/example/daobe/common/config/RedisConfig.java
  src/main/java/com/example/daobe/common/exception/GlobalExceptionHandler.java
  src/main/java/com/example/daobe/notification/application/NotificationDomainEventListener.java
  src/main/java/com/example/daobe/notification/application/NotificationEventListener.java
  src/main/java/com/example/daobe/notification/application/NotificationEventPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationSubscribeService.java
  src/main/java/com/example/daobe/notification/application/dto/DummyResponseDto.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationEventPayloadDto.java
  src/main/java/com/example/daobe/notification/domain/NotificationEmitter.java
  src/main/java/com/example/daobe/notification/infrastructure/redis/RedisNotificationEventPublisher.java
  src/main/java/com/example/daobe/notification/infrastructure/redis/RedisNotificationMessageListener.java
Labels: 기능추가, 리팩토링

#187 사용자 명칭 일관화 및 토큰 검증 로직 리팩토링
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/application/TokenProvider.java
  src/main/java/com/example/daobe/auth/domain/Token.java
  src/main/java/com/example/daobe/auth/infrastructure/jwt/JwtExtractor.java
  src/main/java/com/example/daobe/auth/infrastructure/jwt/JwtProvider.java
  src/main/java/com/example/daobe/auth/infrastructure/security/JwtAuthenticationProvider.java
  src/main/java/com/example/daobe/auth/infrastructure/security/JwtAuthenticationToken.java
Labels: 리팩토링

#188 오브제 도메인 퍼사드 패턴 적용 및 리팩토링
  src/main/java/com/example/daobe/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeDetailInfoDto.java
  src/main/java/com/example/daobe/notification/domain/convert/ObjetInviteEventConvert.java
  src/main/java/com/example/daobe/objet/application/ObjetFacadeService.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetInfoResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateRequestDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetInviteEvent.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#194 사용자 아이디가 null 값인 경우 예외 처리 추가
  src/main/java/com/example/daobe/auth/infrastructure/jwt/JwtExtractor.java
Labels: 버그-심각

#195 채팅 메시지 커서 기반 페이지네이션 추가
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageInfoDto.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageResponseDto.java
  src/main/java/com/example/daobe/chat/domain/ChatMessage.java
  src/main/java/com/example/daobe/chat/domain/repository/ChatMessageRepository.java
  src/main/java/com/example/daobe/chat/exception/ChatExceptionType.java
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
Labels: 버그-일반, 기능추가, 리팩토링

#196 커서 기반 페이징처리 추가
  build.gradle
  src/main/java/com/example/daobe/auth/infrastructure/jwt/JwtExtractor.java
  src/main/java/com/example/daobe/common/config/QueryDslConfig.java
  src/main/java/com/example/daobe/common/response/ApiResponse.java
  src/main/java/com/example/daobe/common/response/SliceApiResponse.java
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/notification/domain/repository/CustomNotificationRepository.java
  src/main/java/com/example/daobe/notification/domain/repository/NotificationRepository.java
  src/main/java/com/example/daobe/notification/domain/repository/dto/NotificationFindCondition.java
  src/main/java/com/example/daobe/notification/infrastructure/querydsl/QueryDslCustomNotificationRepository.java
  src/main/java/com/example/daobe/notification/presentation/NotificationController.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/domain/repository/UserRepository.java
  src/main/java/com/example/daobe/user/domain/repository/UserSearchRepository.java
  src/main/java/com/example/daobe/user/domain/repository/dto/UserSearchCondition.java
  src/main/java/com/example/daobe/user/infrastructure/querydsl/QueryDslUserSearchRepository.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 기능추가, 리팩토링

#198 라운지 탈퇴 기능 구현
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/lounge/domain/LoungeType.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/lounge/presentation/support/LoungeResultType.java
Labels: 기능추가, 리팩토링

#200 오브제 도메인 리팩토링
  src/main/java/com/example/daobe/objet/application/ObjetFacadeService.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetResponseDto.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#201 오브제 도메인 리팩토링
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailResponseDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
Labels: 리팩토링

#205 회원탈퇴 후 재가입시 사용자 상태가 수정되지 않던 문제 수정
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/domain/User.java
Labels: 버그-일반, 리팩토링

#203 feat: 라운지 삭제 이벤트 구독 발행 로직 추가 및 하위 태스크 처리
  src/main/java/com/example/daobe/lounge/application/LoungeService.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeDeleteEvent.java
  src/main/java/com/example/daobe/objet/application/ObjetEventListener.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetResponseDto.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetSignalController.java
Labels: 기능추가

#207 새로운 사용자 생성 이벤트에서 id 값이 null 인 오류 수정
  .github/workflows/backend-prod-cd.yml
  src/main/java/com/example/daobe/user/application/UserService.java
Labels: 버그-심각

#210 회원과 인증 도메인의 책임 분리 및 토큰 핸들링 로직 리팩토링
  .github/workflows/backend-prod-cd.yml
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/application/dto/WithdrawRequestDto.java
  src/main/java/com/example/daobe/auth/infrastructure/jwt/JwtExtractor.java
  src/main/java/com/example/daobe/auth/infrastructure/security/JwtAuthenticationProvider.java
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/UserWithdrawRequestDto.java
  src/main/java/com/example/daobe/user/domain/User.java
  src/main/java/com/example/daobe/user/domain/repository/UserRepository.java
  src/main/java/com/example/daobe/user/exception/UserException.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 리팩토링

#208 라운지 초대시 수락 기능 구현
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharer.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharerStatus.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/lounge/presentation/support/LoungeResultType.java
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
Labels: 기능추가

#211 ChatUser 생성 이벤트 발행시 방어 로직 추가
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/event/ChatUserEventListener.java
Labels: 리팩토링

#215 라운지 초대시 수락하지 않아도 조회 가능한 버그
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharer.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeRepository.java
Labels: 버그-일반

#217 Refactor/objet
  src/main/java/com/example/daobe/objet/application/ObjetFacadeService.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCallParticipantsResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetInfoResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetSharerResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateResponseDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
  src/main/java/com/example/daobe/objet/presentation/ObjetSignalController.java
Labels: 기능추가, 리팩토링

#220 인증 도메인에 있는 회원탈퇴 삭제 및 회원탈퇴시 삭제 시간이 갱신되도록 수정
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
  src/main/java/com/example/daobe/common/domain/BaseTimeEntity.java
  src/main/java/com/example/daobe/user/domain/User.java
Labels: 기능추가, 리팩토링

#222 사용자 콕 찌르기 정책 수정 및 API 쓰로틀링 추가
  build.gradle
  src/main/java/com/example/daobe/common/config/RateLimitConfig.java
  src/main/java/com/example/daobe/common/config/RedisConfig.java
  src/main/java/com/example/daobe/common/throttling/RateLimitInterceptor.java
  src/main/java/com/example/daobe/common/throttling/annotation/RateLimited.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/domain/repository/UserPokeRepository.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
  src/main/java/com/example/daobe/user/infrastructure/redis/RedisUserPokeRepository.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 기능추가, 리팩토링

#221 오브제 도메인 리팩토링
  src/main/java/com/example/daobe/objet/application/ObjetEventListener.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCallParticipantsResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetResponseDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetCreateEvent.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetDeleteEvent.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
  src/main/java/com/example/daobe/user/application/UserService.java
Labels: 리팩토링

#226 라운지 공유자 검증 로직 라운지 도메인으로 리팩토링
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeCreateResponseDto.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeDto.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetSignalRequestDto.java
Labels: 리팩토링

#229 레디스 클라이언트 연결 오류 수정 및 API 요청 제한 예외 추가
  src/main/java/com/example/daobe/common/config/RedisConfig.java
  src/main/java/com/example/daobe/common/throttling/RateLimitException.java
  src/main/java/com/example/daobe/common/throttling/RateLimitExceptionType.java
  src/main/java/com/example/daobe/common/throttling/RateLimitInterceptor.java
Labels: 버그-심각, 기능추가, 리팩토링

#232 로깅 필터 및 유틸 클래스 리팩토링
  src/main/java/com/example/daobe/common/logging/LoggingMediaType.java
  src/main/java/com/example/daobe/common/logging/ReqResLoggingFilter.java
  src/main/java/com/example/daobe/common/utils/DaoFileExtensionUtils.java
  src/main/java/com/example/daobe/common/utils/DaoStreamUtils.java
  src/main/java/com/example/daobe/common/utils/DaoStringUtils.java
Labels: 리팩토링

#230 채팅 Redis Pub/Sub 적용
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageInfoDto.java
  src/main/java/com/example/daobe/chat/exception/ChatExceptionType.java
  src/main/java/com/example/daobe/chat/infrastructure/RedisSubscriber.java
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
  src/main/java/com/example/daobe/common/config/RedisConfig.java
Labels: 기능추가, 리팩토링

#235 chore: 유저 오브제 목록 조회 응답 dto 수정
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeResponseDto.java
Labels: 리팩토링

#236 채팅 메시지 전송 요청 제한을 위한 어노테이션 추가
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
Labels: 기능추가

#239 오브제 리팩토링
  src/main/java/com/example/daobe/notification/domain/convert/ObjetInviteEventConvert.java
  src/main/java/com/example/daobe/objet/application/ObjetEventListener.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDeleteResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetInfoResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateResponseDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/ObjetStatus.java
  src/main/java/com/example/daobe/objet/domain/ObjetType.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetCallRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/exception/ObjetExceptionType.java
  src/main/java/com/example/daobe/objet/infrastructure/redis/RedisObjetCallRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#243 refactor: 유저 오브제 조회 로직 리팩토링
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
Labels: 버그-일반, 리팩토링

#244 회원 도메인 로직 리팩토링 및 기본 테스트 환경 구성 추가
  build.gradle
  src/main/java/com/example/daobe/user/domain/DefaultNicknamePolicy.java
  src/main/java/com/example/daobe/user/domain/ReasonType.java
  src/main/java/com/example/daobe/user/domain/User.java
  src/main/java/com/example/daobe/user/domain/UserStatus.java
  src/test/java/com/example/daobe/common/fixtures/UserFixtures.java
  src/test/resources/application.yml
Labels: 리팩토링, 테스트

#247 라운지 도메인 단위 테스트 코드 추가 및 리팩토링
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharer.java
  src/main/java/com/example/daobe/lounge/domain/LoungeStatus.java
  src/main/java/com/example/daobe/lounge/domain/LoungeType.java
  src/test/java/com/example/daobe/common/fixtures/LoungeFixtures.java
  src/test/java/com/example/daobe/common/fixtures/LoungeSharerFixtures.java
  src/test/java/com/example/daobe/lounge/domain/LoungeSharerTest.java
  src/test/java/com/example/daobe/lounge/domain/LoungeTest.java
  src/test/java/com/example/daobe/lounge/domain/LoungeTypeTest.java
Labels: 리팩토링, 테스트

#249 메서드별 호출 및 실행 시간에 대한 로깅 AOP 추가
  src/main/java/com/example/daobe/common/logging/method/MethodLoggingAspect.java
  src/main/java/com/example/daobe/common/logging/method/MethodLoggingContext.java
  src/main/java/com/example/daobe/common/logging/method/MethodLoggingFormatter.java
Labels: 기능추가

#252 채팅 도메인 레디스 구독 로직 및 의존성 사이클 제거
  src/main/java/com/example/daobe/chat/application/ChatMessageService.java
  src/main/java/com/example/daobe/chat/infrastructure/redis/RedisChatMessageListener.java
  src/main/java/com/example/daobe/chat/infrastructure/redis/RedisMessageEventPublisher.java
  src/main/java/com/example/daobe/chat/infrastructure/redis/RedisMessageListener.java
  src/main/java/com/example/daobe/common/config/RedisConfig.java
Labels: 리팩토링

#254 이미지 업로드에 @Deprecated된 메서드 삭제 및 캐싱 처리 로직 리팩토링
  src/main/java/com/example/daobe/common/config/S3Properties.java
  src/main/java/com/example/daobe/upload/application/UploadService.java
  src/main/java/com/example/daobe/upload/application/dto/UploadImageResponse.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3ImageClient.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3Uploader.java
  src/main/resources/application-local.yml
Labels: 리팩토링
