Repository 100-hours-a-week/10-team-joytas-dao-be, pull requests merged in 2024-08, with the labels that each got.

#3 개발을 위한 기본적인 설정 파일들을 추가
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  .github/workflows/backend-dev-cd.yml
  Dockerfile-dev
  src/main/java/com/example/daobe/common/controller/HealthController.java
Labels: 기능추가

#4 헬스 체크 엔드포인트 수정
  build.gradle
  src/main/java/com/example/daobe/common/controller/HealthController.java
Labels: 버그-심각

#6 기본 도메인 엔티티 및 연관 관계 설정 추가
  src/main/java/com/example/daobe/lounge/entity/Lounge.java
  src/main/java/com/example/daobe/myroom/entity/MyRoom.java
  src/main/java/com/example/daobe/notification/entity/Notification.java
  src/main/java/com/example/daobe/objet/entity/Objet.java
  src/main/java/com/example/daobe/shared/entity/UserLounge.java
  src/main/java/com/example/daobe/shared/entity/UserObjet.java
  src/main/java/com/example/daobe/user/entity/User.java
Labels: 기능추가

#7 환경변수 예제 파일 추가
  .env.example
Labels: 기능추가

#8 기본 엔티티 추가
  src/main/java/com/example/daobe/common/entity/BaseTimeEntity.java
Labels: 기능추가

#9 오브제 기본 구성
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
Labels: 기능추가

#10 라운지 기본 구성
  src/main/java/com/example/daobe/lounge/controller/LoungeController.java
  src/main/java/com/example/daobe/lounge/repository/LoungeRepository.java
  src/main/java/com/example/daobe/lounge/service/LoungeService.java
Labels: 기능추가

#11 데이터베이스 및 사용자 엔티티 빌더 패턴 추가
  .env.example
  src/main/java/com/example/daobe/user/entity/User.java
  src/main/resources/application-local.yml
Labels: 기능추가

#13 사용자 JPA 리포지토리 추가
  src/main/java/com/example/daobe/user/respository/UserRepository.java
Labels: 기능추가

#16 feature : 오브제 생성 api 구현 (이미지 제외)
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/dto/ObjetCreateResponseDto.java
  src/main/java/com/example/daobe/objet/entity/ObjectStatus.java
  src/main/java/com/example/daobe/objet/entity/Objet.java
  src/main/java/com/example/daobe/objet/entity/ObjetType.java
  src/main/java/com/example/daobe/objet/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
  src/main/java/com/example/daobe/shared/entity/UserObjet.java
Labels: 기능추가

#20 JWT 발급 로직 및 쿠키 설정 추가
  .env.example
  src/main/java/com/example/daobe/auth/dto/TokenResponseDto.java
  src/main/java/com/example/daobe/auth/oauth/CustomAuthorizationRequestRepository.java
  src/main/java/com/example/daobe/auth/oauth/OAuthService.java
  src/main/java/com/example/daobe/auth/oauth/OAuthSuccessHandler.java
  src/main/java/com/example/daobe/auth/service/AuthService.java
  src/main/java/com/example/daobe/common/config/SecurityConfig.java
  src/main/java/com/example/daobe/common/controller/cookie/CookieHandler.java
  src/main/java/com/example/daobe/common/controller/cookie/CookieProperties.java
  src/main/resources/application-local.yml
Labels: 기능추가

#22 라운지 상세 조회 기능 구현
  src/main/java/com/example/daobe/lounge/controller/LoungeController.java
  src/main/java/com/example/daobe/lounge/dto/LoungeCreateResponseDto.java
  src/main/java/com/example/daobe/lounge/dto/LoungeDetailInfoDto.java
  src/main/java/com/example/daobe/lounge/dto/LoungeInfoDto.java
  src/main/java/com/example/daobe/lounge/service/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/service/LoungeService.java
Labels: 기능추가

#23 오브제 생성 : 이미지 업로드 추가
  build.gradle
  src/main/java/com/example/daobe/common/config/S3Config.java
  src/main/java/com/example/daobe/common/config/S3Properties.java
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/dto/ObjetInfoDto.java
  src/main/java/com/example/daobe/objet/exception/ObjetException.java
  src/main/java/com/example/daobe/objet/exception/ObjetExceptionType.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
  src/main/java/com/example/daobe/upload/application/ImageClient.java
  src/main/java/com/example/daobe/upload/application/UploadService.java
  src/main/java/com/example/daobe/upload/application/dto/UploadImageResponse.java
  src/main/java/com/example/daobe/upload/exception/UploadException.java
  src/main/java/com/example/daobe/upload/exception/UploadExceptionType.java
  src/main/java/com/example/daobe/upload/s3/S3ImageClient.java
  src/main/java/com/example/daobe/upload/s3/S3Uploader.java
  src/main/resources/application-local.yml
Labels: 기능추가

#25 라운지 유저 초대 기능 구현
  src/main/java/com/example/daobe/lounge/controller/LoungeController.java
  src/main/java/com/example/daobe/lounge/dto/LoungeCreateResponseDto.java
  src/main/java/com/example/daobe/lounge/dto/LoungeInfoDto.java
  src/main/java/com/example/daobe/lounge/dto/LoungeInviteDto.java
  src/main/java/com/example/daobe/lounge/entity/InviteStatus.java
  src/main/java/com/example/daobe/lounge/entity/Lounge.java
  src/main/java/com/example/daobe/lounge/service/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/service/LoungeService.java
  src/main/java/com/example/daobe/shared/entity/UserLounge.java
  src/main/java/com/example/daobe/shared/repository/UserLoungeRepository.java
Labels: 기능추가

#26 오브제 조회 / 상세 조회 구현
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/dto/ObjetInfoDto.java
  src/main/java/com/example/daobe/objet/entity/Objet.java
  src/main/java/com/example/daobe/objet/entity/ObjetStatus.java
  src/main/java/com/example/daobe/objet/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
  src/main/java/com/example/daobe/shared/repository/UserObjetRepository.java
Labels: 기능추가

#27 토큰 재발행 및 로그아웃 로직 추가
  src/main/java/com/example/daobe/auth/controller/AuthController.java
  src/main/java/com/example/daobe/auth/service/AuthService.java
Labels: 기능추가

#30 로컬 개발 환경 기본 데이터베이스 수정
  .env.example
  build.gradle
  docker/docker-compose.yml
  docker/init.sql
  src/main/resources/application-local.yml
Labels: 기능추가

#31 시큐리티 경로 및 예외 처리 추가
  src/main/java/com/example/daobe/auth/oauth/OAuthSuccessHandler.java
  src/main/java/com/example/daobe/auth/security/JwtAuthenticationFilter.java
  src/main/java/com/example/daobe/auth/security/JwtAuthenticationProvider.java
  src/main/java/com/example/daobe/auth/security/exception/SecurityException.java
  src/main/java/com/example/daobe/auth/security/exception/SecurityExceptionType.java
  src/main/java/com/example/daobe/auth/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/example/daobe/auth/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/example/daobe/common/config/SecurityConfig.java
  src/main/resources/application-local.yml
Labels: 기능추가

#37 커스텀 로깅 처리 기능 추가
  .gitignore
  src/main/java/com/example/daobe/common/config/LoggingConfig.java
  src/main/java/com/example/daobe/common/logging/MdcLoggingFilter.java
  src/main/java/com/example/daobe/common/logging/ReqResLoggingFilter.java
  src/main/java/com/example/daobe/common/utils/DaoStreamUtils.java
  src/main/resources/logback-spring.xml
  src/main/resources/logs/console-appender.xml
  src/main/resources/logs/file/error-appender.xml
  src/main/resources/logs/file/info-appender.xml
Labels: 기능추가

#38 라운지 삭제 기능 추가 및 리팩토링
  src/main/java/com/example/daobe/lounge/controller/LoungeController.java
  src/main/java/com/example/daobe/lounge/entity/InviteStatus.java
  src/main/java/com/example/daobe/lounge/entity/Lounge.java
  src/main/java/com/example/daobe/lounge/entity/LoungeResult.java
  src/main/java/com/example/daobe/lounge/service/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/service/LoungeService.java
Labels: 기능추가

#41 오브제 - 인가 적용
  src/main/java/com/example/daobe/lounge/exception/LoungeException.java
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/exception/ObjetException.java
  src/main/java/com/example/daobe/objet/exception/ObjetExceptionType.java
  src/main/java/com/example/daobe/objet/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
  src/main/java/com/example/daobe/user/exception/UserException.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
Labels: 기능추가

#42 오브제 삭제 기능 구현
  src/main/java/com/example/daobe/objet/controller/ObjetController.java
  src/main/java/com/example/daobe/objet/entity/Objet.java
  src/main/java/com/example/daobe/objet/service/ObjetService.java
Labels: 기능추가

#43 랜덤 닉네임 생성 로직 추가
  src/main/java/com/example/daobe/auth/oauth/OAuthService.java
  src/main/java/com/example/daobe/auth/oauth/OAuthSuccessHandler.java
  src/main/java/com/example/daobe/auth/service/AuthService.java
  src/main/java/com/example/daobe/common/config/SecurityConfig.java
  src/main/java/com/example/daobe/user/entity/DefaultNicknamePolicy.java
  src/main/java/com/example/daobe/user/entity/User.java
  src/main/java/com/example/daobe/user/entity/UserStatus.java
Labels: 기능추가

#48 쿼리 카운터 AOP 및 로깅 추가
  src/main/java/com/example/daobe/common/config/LoggingConfig.java
  src/main/java/com/example/daobe/common/logging/ReqResLoggingFilter.java
  src/main/java/com/example/daobe/common/logging/query/ConnectionMethodInterceptor.java
  src/main/java/com/example/daobe/common/logging/query/QueryCountInterceptor.java
  src/main/java/com/example/daobe/common/logging/query/QueryCounter.java
  src/main/java/com/example/daobe/common/logging/query/QueryCounterAop.java
  src/main/java/com/example/daobe/common/logging/query/QueryMethodInterceptor.java
Labels: 기능추가

#52 refactor: 오브제 도메인 패키지 구조 레이어드 아키텍처로 변경
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeDetailInfoDto.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateRequestDto.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/ObjetStatus.java
  src/main/java/com/example/daobe/objet/domain/ObjetType.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
  src/main/java/com/example/daobe/shared/entity/UserObjet.java
Labels: 리팩토링

#53 엔티티 네이밍 및 위치 이동
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/ObjetSharer.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/shared/repository/UserObjetRepository.java
Labels: 리팩토링

#54 유저-라운지 라운지 도메인에 포함하도록 수정
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharer.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
  src/main/java/com/example/daobe/shared/repository/UserLoungeRepository.java
Labels: 리팩토링

#55 오브제 조회 로직 수정
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#56 회원 도메인 패키지 구조 변경 및 API 추가
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeService.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/lounge/domain/LoungeSharer.java
  src/main/java/com/example/daobe/myroom/entity/MyRoom.java
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/ObjetSharer.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/UpdateProfileRequestDto.java
  src/main/java/com/example/daobe/user/application/dto/UpdateProfileResponseDto.java
  src/main/java/com/example/daobe/user/application/dto/UserInfoResponseDto.java
  src/main/java/com/example/daobe/user/domain/DefaultNicknamePolicy.java
  src/main/java/com/example/daobe/user/domain/User.java
  src/main/java/com/example/daobe/user/domain/UserStatus.java
  src/main/java/com/example/daobe/user/domain/repository/UserRepository.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
  src/main/java/com/example/daobe/user/repository/UserRepository.java
Labels: 기능추가, 리팩토링

#59 패키지명 수정으로 인한 병합충돌 문제 해결
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/myroom/application/MyRoomService.java
  src/main/java/com/example/daobe/myroom/application/dto/CreatedMyRoomRequestDto.java
  src/main/java/com/example/daobe/myroom/application/dto/CreatedMyRoomResponseDto.java
  src/main/java/com/example/daobe/myroom/application/dto/MyRoomInfoResponseDto.java
  src/main/java/com/example/daobe/myroom/application/dto/UpdateMyRoomRequestDto.java
  src/main/java/com/example/daobe/myroom/application/dto/UpdateMyRoomResponseDto.java
  src/main/java/com/example/daobe/myroom/domain/MyRoom.java
  src/main/java/com/example/daobe/myroom/domain/repository/MyRoomRepository.java
  src/main/java/com/example/daobe/myroom/exception/MyRoomException.java
  src/main/java/com/example/daobe/myroom/exception/MyRoomExceptionType.java
  src/main/java/com/example/daobe/myroom/presentation/MyRoomController.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
Labels: 버그-일반

#62 쿠키 도메인 옵션에 대한 유틸 클래스 수정
  src/main/java/com/example/daobe/common/presentation/cookie/CookieHandler.java
Labels: 리팩토링

#64 라운지 상세 조회 로직 수정
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/objet/domain/ObjetSharer.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
Labels: 리팩토링

#63 파일 업로드 용량 및 확장자 검증
  src/main/java/com/example/daobe/common/utils/DaoFileExtensionUtils.java
  src/main/java/com/example/daobe/objet/exception/ObjetExceptionType.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
  src/main/resources/application-local.yml
Labels: 기능추가

#67 유저 오브제 조회 기능 추가
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeInfoDto.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 기능추가

#70 오브제 공유자 명칭 변경 관련 작업
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetCreateRequestDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetUpdateRequestDto.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 리팩토링

#71 도메인 패키지 명 수정 및 기본 엔티티 클래스가 추가되지 않은 엔티티 수정
  src/main/java/com/example/daobe/common/domain/BaseTimeEntity.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/myroom/domain/MyRoom.java
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/user/domain/User.java
Labels: 리팩토링

#72 사용자 정보 조회 응답 형식 수정
  src/main/java/com/example/daobe/user/application/dto/UserInfoResponseDto.java
Labels: 리팩토링

#73 사용자 정보 수정 요청에 프로필 이미지 업로드 추가
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 기능추가

#74 시그널링 서버 인증 추가
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/application/dto/SignalingAuthRequestDto.java
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
Labels: 기능추가

#78 오브제 상세조회에 타입 추가
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetDetailInfoDto.java
Labels: 리팩토링

#79 회원탈퇴 API 구현
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/application/dto/WithdrawRequestDto.java
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
  src/main/java/com/example/daobe/user/domain/ReasonType.java
  src/main/java/com/example/daobe/user/domain/User.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
Labels: 기능추가

#83 feat: 유저 오브제 조회에 오브제 타입 추가
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeInfoDto.java
Labels: 기능추가

#85 SSE 실시간 알림 기능 추가
  src/main/java/com/example/daobe/common/config/AsyncConfig.java
  src/main/java/com/example/daobe/common/decorator/MdcDecorator.java
  src/main/java/com/example/daobe/common/domain/DomainEvent.java
  src/main/java/com/example/daobe/common/logging/LoggingMediaType.java
  src/main/java/com/example/daobe/common/logging/ReqResLoggingFilter.java
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationPayload.java
  src/main/java/com/example/daobe/notification/domain/NotificationEmitter.java
  src/main/java/com/example/daobe/notification/domain/NotificationEventType.java
  src/main/java/com/example/daobe/notification/domain/repository/EmitterRepository.java
  src/main/java/com/example/daobe/notification/domain/repository/NotificationRepository.java
  src/main/java/com/example/daobe/notification/infrastructure/in_memory/InMemoryEmitterRepository.java
  src/main/java/com/example/daobe/notification/presentation/NotificationController.java
  src/main/resources/application-local.yml
Labels: 기능추가

#86 라운지 초대 알림 기능 추가
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInviteEvent.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
Labels: 기능추가

#90 LazyInitializationException 해결
  src/main/java/com/example/daobe/auth/application/AuthService.java
Labels: 버그-심각

#91 시그널링 관련 로직 오브제 도메인으로 이동
  src/main/java/com/example/daobe/auth/application/AuthService.java
  src/main/java/com/example/daobe/auth/application/dto/SignalingAuthRequestDto.java
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetSignalRequestDto.java
  src/main/java/com/example/daobe/objet/presentation/ObjetSignalController.java
Labels: 리팩토링

#93 오브제 서비스 @Transactional 처리
  src/main/java/com/example/daobe/objet/application/ObjetService.java
Labels: 리팩토링

#95 채팅 기능 구현 및 리팩토링
  src/main/java/com/example/daobe/chat/application/ChatRoomService.java
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/application/dto/ChatRoomTokenDto.java
  src/main/java/com/example/daobe/chat/domain/ChatMessage.java
  src/main/java/com/example/daobe/chat/domain/ChatRoom.java
  src/main/java/com/example/daobe/chat/domain/MessageType.java
  src/main/java/com/example/daobe/chat/domain/repository/ChatMessageRepository.java
  src/main/java/com/example/daobe/chat/domain/repository/ChatRoomRepository.java
  src/main/java/com/example/daobe/chat/exception/ChatRoomException.java
  src/main/java/com/example/daobe/chat/exception/ChatRoomExceptionType.java
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
  src/main/java/com/example/daobe/common/config/MongoConfig.java
  src/main/java/com/example/daobe/common/config/SecurityConfig.java
  src/main/java/com/example/daobe/common/config/WebSocketConfig.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeDetailInfoDto.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeRepository.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
Labels: 기능추가, 리팩토링

#96 채팅 도메인 엔티티에서 임포트 경로 수정
  src/main/java/com/example/daobe/chat/domain/ChatRoom.java
Labels: 버그-심각

#97 알림 기능 커스텀 예외 처리 적용
  src/main/java/com/example/daobe/notification/domain/NotificationEmitter.java
  src/main/java/com/example/daobe/notification/domain/NotificationEventType.java
  src/main/java/com/example/daobe/notification/exception/NotificationException.java
  src/main/java/com/example/daobe/notification/exception/NotificationExceptionType.java
Labels: 기능추가

#98 Refactor: 유저 오브제 dto에 라운지 ID 추가
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeInfoDto.java
Labels: 리팩토링

#103 도커 이미지 정리 스크립트 수정
  .github/workflows/backend-dev-cd.yml
Labels: 버그-일반, 리팩토링

#101 @AuthenticationPrincipal 제거
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
Labels: 리팩토링

#104 오브제 음성채팅 참여 인원수 조회 기능 구현
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/infrastructure/redis/ObjetCallRepository.java
  src/main/java/com/example/daobe/objet/infrastructure/redis/RedisObjetCallRepository.java
Labels: 기능추가

#106 오브제 음성 통화기능에서 레디스 접근 로직 오류수정 및 리팩토링
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetCallRepository.java
  src/main/java/com/example/daobe/objet/infrastructure/redis/RedisObjetCallRepository.java
Labels: 버그-심각, 리팩토링

#105 채팅 관련 엔드포인트 수정
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
Labels: 리팩토링

#108 배포 실패시 디스코드 알림 기능 추가
  .github/workflows/deploy-failure-notice.yml
Labels: 기능추가

#111 오브제 초대 기능 추가
  src/main/java/com/example/daobe/notification/domain/NotificationEventType.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetInviteEvent.java
Labels: 기능추가

#115 일정 시간이 지나면 세션 초기화 되는 문제 해결
  src/main/java/com/example/daobe/chat/application/ChatService.java
Labels: 버그-심각

#116 채팅 세션 만료 버그 해결 및 채팅방 퇴장 기능 추가
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/application/dto/ChatMessageDto.java
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
Labels: 버그-심각, 기능추가

#117 채팅방 입장시 다른 유저 이름이 조회되는 버그 로그 추가
  src/main/java/com/example/daobe/chat/application/ChatService.java
Labels: 버그-심각, 버그-일반

#118 라운지 상세 조회시 삭제되지 않은 오브제 조회되는 문제 해결
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
Labels: 버그-일반, 기능추가, 리팩토링

#122 라운지내 소속된 사용자 검색 API 추가
  src/main/java/com/example/daobe/lounge/application/LoungeSearchService.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeSharerInfoResponseDto.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeSearchController.java
Labels: 기능추가

#124 SSE 알림 페이로드 수정 및 알림 저장 및 조회 로직 추가
  src/main/java/com/example/daobe/common/domain/DomainEvent.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInviteEvent.java
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/notification/application/NotificationSubscribeService.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationPayload.java
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/notification/domain/NotificationEventType.java
  src/main/java/com/example/daobe/notification/domain/convert/DomainEventConvert.java
  src/main/java/com/example/daobe/notification/domain/convert/DomainEventConvertMapper.java
  src/main/java/com/example/daobe/notification/domain/convert/LoungeInviteEventConvert.java
  src/main/java/com/example/daobe/notification/domain/convert/ObjetInviteEventConvert.java
  src/main/java/com/example/daobe/notification/domain/convert/dto/DomainInfo.java
  src/main/java/com/example/daobe/notification/domain/repository/NotificationRepository.java
  src/main/java/com/example/daobe/notification/exception/NotificationExceptionType.java
  src/main/java/com/example/daobe/notification/presentation/NotificationController.java
  src/main/java/com/example/daobe/notification/presentation/NotificationSubscribeController.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetInviteEvent.java
Labels: 기능추가, 리팩토링

#126 알림 상세조회시 보낸 사용자 정보 추가
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/notification/domain/repository/NotificationRepository.java
Labels: 버그-일반, 리팩토링

#127 로컬 몽고 디비 및 스프링 애플리케이션 설정 수정
  docker/init.js
  src/main/resources/application-local.yml
Labels: 리팩토링

#128 회원 서비스에 식별자로 회원 정보를 가져올 수 있는 로직 추가
  src/main/java/com/example/daobe/user/application/UserService.java
Labels: 기능추가

#130 SSE 알림 응답 및 알림 조회 응답 수정
  src/main/java/com/example/daobe/notification/application/NotificationPublisher.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationPayload.java
Labels: 기능추가, 리팩토링

#139 응답이 카멜 케이스로 오는 버그 수정
  src/main/java/com/example/daobe/notification/application/dto/NotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/domain/convert/dto/DomainInfo.java
Labels: 버그-일반

#140 fix: 오브제 음성채팅 권한 검증 objet_id -> lounge_id로 변경 #136
  src/main/java/com/example/daobe/objet/application/ObjetSignalService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetSignalRequestDto.java
Labels: 버그-일반

#143 유저의 라운지 최대 개수 제한 기능 구현
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
Labels: 기능추가

#142 알림 커스텀 예외처리 추가
  src/main/java/com/example/daobe/notification/domain/NotificationEmitter.java
  src/main/java/com/example/daobe/notification/domain/convert/DomainEventConvertMapper.java
  src/main/java/com/example/daobe/notification/domain/convert/LoungeInviteEventConvert.java
  src/main/java/com/example/daobe/notification/domain/convert/ObjetInviteEventConvert.java
  src/main/java/com/example/daobe/notification/exception/NotificationExceptionType.java
Labels: 기능추가, 리팩토링

#145 이미지 업로드 로직과 사용자 정보 수정 로직 분리
  src/main/java/com/example/daobe/upload/application/UploadService.java
  src/main/java/com/example/daobe/upload/application/dto/UploadImageResponseDto.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3ImageClient.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3Uploader.java
  src/main/java/com/example/daobe/upload/presentation/UploadController.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/UpdateProfileRequestDto.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 리팩토링

#148 사용자 프로필 정보 수정 로직 변경
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/UpdateProfileRequestDto.java
  src/main/java/com/example/daobe/user/domain/User.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 리팩토링

#154 라운지 내 유저 검색 기능 기존 로직과 통합
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSearchService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeSearchController.java
  src/main/java/com/example/daobe/lounge/presentation/support/LoungeResultType.java
Labels: 리팩토링

#156 사용자 콕 찌르기 기능 추가
  src/main/java/com/example/daobe/common/utils/DaoStringUtils.java
  src/main/java/com/example/daobe/notification/domain/NotificationEventType.java
  src/main/java/com/example/daobe/notification/domain/convert/UserPokeEventConvert.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/UserPokeRequestDto.java
  src/main/java/com/example/daobe/user/domain/event/UserPokeEvent.java
  src/main/java/com/example/daobe/user/domain/repository/UserPokeRepository.java
  src/main/java/com/example/daobe/user/exception/UserExceptionType.java
  src/main/java/com/example/daobe/user/infrastructure/redis/RedisUserPokeRepository.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 기능추가

#158 레디스 저장소 접근 및 문자열 유틸 클래스 리팩토링
  src/main/java/com/example/daobe/auth/infrastructure/redis/RedisTokenRepository.java
  src/main/java/com/example/daobe/common/utils/DaoStringUtils.java
  src/main/java/com/example/daobe/objet/infrastructure/redis/RedisObjetCallRepository.java
  src/main/java/com/example/daobe/user/infrastructure/redis/RedisUserPokeRepository.java
Labels: 리팩토링

#160 콕 찌르기 및 알림 읽기시 발생한 오류 수정
  src/main/java/com/example/daobe/notification/domain/Notification.java
  src/main/java/com/example/daobe/user/application/UserService.java
Labels: 버그-심각
