Repository 100-hours-a-week/10-team-joytas-dao-be, pull requests merged in 2024-10, with the labels that each got.

#257 오브제 목록 조회 - 커서 기반 페이지네이션 적용
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetMeResponseDto.java
  src/main/java/com/example/daobe/objet/domain/repository/CustomObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetRepository.java
  src/main/java/com/example/daobe/objet/domain/repository/dto/ObjetFindCondition.java
  src/main/java/com/example/daobe/objet/infrastructure/querydsl/QueryDslCustomObjetRepository.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
Labels: 기능추가

#260 오브제 목록 조회 페이징 처리 조건 타입 수정
  src/main/java/com/example/daobe/objet/domain/repository/dto/ObjetFindCondition.java
Labels: 버그-일반

#264 최대 개수의 라운지에 소속되어도 초대 수락되는 버그 해결
  src/main/java/com/example/daobe/lounge/application/LoungeFacadeService.java
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/repository/LoungeSharerRepository.java
Labels: 버그-일반

#268 라운지 탈퇴 이벤트 추가
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeWithdrawEvent.java
Labels: 기능추가

#270 오브제 공유자 활성 상태 추가
  src/main/java/com/example/daobe/objet/application/ObjetEventListener.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/domain/Objet.java
  src/main/java/com/example/daobe/objet/domain/ObjetSharer.java
  src/main/java/com/example/daobe/objet/domain/ObjetSharerStatus.java
  src/main/java/com/example/daobe/objet/domain/repository/ObjetSharerRepository.java
  src/main/java/com/example/daobe/objet/infrastructure/querydsl/QueryDslCustomObjetRepository.java
  src/main/resources/db/migration/V4__add_status_in_objets_sharer_status.sql
Labels: 기능추가

#259 채팅, 라운지 도메인 변수명 통일 및 리팩토링
  src/main/java/com/example/daobe/chat/application/ChatService.java
  src/main/java/com/example/daobe/chat/domain/repository/ChatUserRepository.java
  src/main/java/com/example/daobe/lounge/application/LoungeService.java
  src/main/java/com/example/daobe/lounge/application/dto/LoungeDetailInfoDto.java
  src/main/java/com/example/daobe/lounge/domain/Lounge.java
Labels: 리팩토링

#275 라운지 초대 수락 이벤트 발행 기능 추가
  src/main/java/com/example/daobe/lounge/application/LoungeSharerService.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInviteAcceptedEvent.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInvitedEvent.java
Labels: 기능추가, 리팩토링

#277 라운지 초대 이벤트에서 존재하지 않는 필드를 호출 하던 문제 수정
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInvitedEvent.java
  src/main/java/com/example/daobe/lounge/exception/LoungeExceptionType.java
Labels: 버그-심각

#285 라운지 이름 검증에 필요한 정규식 수정
  src/main/java/com/example/daobe/lounge/domain/LoungeName.java
Labels: 버그-일반, 리팩토링

#290 TX Outbox 패턴 적용 및 알림 이벤트 개선
  build.gradle
  src/main/java/com/example/daobe/common/config/ScheduleConfig.java
  src/main/java/com/example/daobe/common/domain/DomainEvent.java
  src/main/java/com/example/daobe/common/domain/DomainEventConverter.java
  src/main/java/com/example/daobe/common/outbox/Outbox.java
  src/main/java/com/example/daobe/common/outbox/OutboxRelayScheduler.java
  src/main/java/com/example/daobe/common/outbox/OutboxRepository.java
  src/main/java/com/example/daobe/common/outbox/OutboxService.java
  src/main/java/com/example/daobe/lounge/domain/event/LoungeInvitedEvent.java
  src/main/java/com/example/daobe/notification/application/NotificationEventListener.java
  src/main/java/com/example/daobe/notification/application/NotificationEventMessageListener.java
  src/main/java/com/example/daobe/notification/application/NotificationEventRecodeListener.java
  src/main/java/com/example/daobe/notification/application/NotificationExternalEventPublisher.java
  src/main/java/com/example/daobe/notification/application/NotificationSubscribeService.java
  src/main/java/com/example/daobe/notification/infrastructure/redis/RedisNotificationExternalEventPublisher.java
  src/main/java/com/example/daobe/notification/infrastructure/redis/RedisNotificationMessageListener.java
  src/main/java/com/example/daobe/objet/application/ObjetSharerService.java
  src/main/java/com/example/daobe/objet/domain/event/ObjetInviteEvent.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/domain/event/UserPokeEvent.java
  src/main/resources/db/migration/V5__add_outbox_table.sql
Labels: 기능추가, 리팩토링

#291 전역 응답 처리 일관화 리팩토링
  src/main/java/com/example/daobe/auth/presentation/AuthController.java
  src/main/java/com/example/daobe/chat/presentation/ChatController.java
  src/main/java/com/example/daobe/common/presentation/GlobalResponseBodyAdvice.java
  src/main/java/com/example/daobe/common/presentation/response/ApiResponseDto.java
  src/main/java/com/example/daobe/common/response/ApiResponse.java
  src/main/java/com/example/daobe/common/response/SliceApiResponse.java
  src/main/java/com/example/daobe/lounge/presentation/LoungeController.java
  src/main/java/com/example/daobe/lounge/presentation/support/LoungeResultType.java
  src/main/java/com/example/daobe/myroom/presentation/MyRoomController.java
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/notification/application/dto/NotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/application/dto/PagedNotificationInfoResponseDto.java
  src/main/java/com/example/daobe/notification/presentation/NotificationController.java
  src/main/java/com/example/daobe/objet/application/ObjetService.java
  src/main/java/com/example/daobe/objet/application/dto/ObjetResponseDto.java
  src/main/java/com/example/daobe/objet/application/dto/PagedObjetResponseDto.java
  src/main/java/com/example/daobe/objet/presentation/ObjetController.java
  src/main/java/com/example/daobe/objet/presentation/ObjetSignalController.java
  src/main/java/com/example/daobe/upload/presentation/UploadController.java
  src/main/java/com/example/daobe/user/application/UserService.java
  src/main/java/com/example/daobe/user/application/dto/PagedUserInfoResponseDto.java
  src/main/java/com/example/daobe/user/presentation/UserController.java
Labels: 리팩토링

#292 알림 조회 및 사용자 검색시 발생하던 오류 수정
  src/main/java/com/example/daobe/notification/application/NotificationService.java
  src/main/java/com/example/daobe/user/application/UserService.java
Labels: 버그-심각

#298 S3 Presigned URL 발행 기능 추가
  src/main/java/com/example/daobe/common/config/S3Config.java
  src/main/java/com/example/daobe/upload/application/ImageClient.java
  src/main/java/com/example/daobe/upload/application/UploadService.java
  src/main/java/com/example/daobe/upload/application/dto/UploadImageUrlResponseDto.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3ImageClient.java
  src/main/java/com/example/daobe/upload/infrastructure/s3/S3PresignHandler.java
  src/main/java/com/example/daobe/upload/presentation/UploadController.java
Labels: 기능추가
